# Generated by Django 4.0.4 on 2025-01-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('activo', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.PositiveIntegerField()),
                ('unidad_duracion', models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5)),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField(blank=True, null=True)),
                ('horas_diarias', models.PositiveIntegerField(default=0)),
                ('direccion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Terminado', 'Terminado')], default='En curso', max_length=15)),
                ('activar_evaluacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('XX', 'XX')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_preguntas', to='core.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.PositiveIntegerField()),
                ('unidad_duracion', models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5)),
                ('horas_diarias', models.PositiveIntegerField()),
                ('temario', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField()),
                ('correctas', models.IntegerField(default=0)),
                ('incorrectas', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asistente', to='core.asistente')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asistentes', to='core.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField(default=False)),
                ('evaluacion_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_respuestas', to='core.evaluacion_pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('puntuacion', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_asistente', to='core.asistente')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_curso', to='core.tema'),
        ),
        migrations.CreateModel(
            name='CapacitacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Capacitacion/', verbose_name='Foto')),
                ('activar_para_reporte', models.BooleanField(choices=[('SI', True), ('NO', False)], default=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_foto', to='core.capacitacion')),
            ],
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_curso', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_capacitacion', to='core.instructor'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tema_curso', to='core.tema'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistentes', to='core.capacitacion'),
        ),
    ]
