# Generated by Django 4.0.4 on 2024-12-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Capacitacion',
        ),
        migrations.RenameField(
            model_name='asistente',
            old_name='curso',
            new_name='capacitacion',
        ),
    ]
