# Generated by Django 4.0.4 on 2024-12-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_curso_capacitacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogo',
            new_name='Curso',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitaciones', to='core.instructor'),
        ),
    ]
