# Generated by Django 4.0.4 on 2025-01-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_evaluacion_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.PositiveIntegerField()),
                ('unidad_duracion', models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5)),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField(blank=True, null=True)),
                ('horas_diarias', models.PositiveIntegerField(default=0)),
                ('direccion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Terminado', 'Terminado')], default='En curso', max_length=15)),
                ('activar_evaluacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('XX', 'XX')], default='NO', max_length=2)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_curso', to='core.empresa')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_curso', to='core.instructor')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tema_curso', to='core.tema')),
            ],
        ),
        migrations.CreateModel(
            name='CursoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Curso/', verbose_name='Foto')),
                ('activar_para_reporte', models.BooleanField(choices=[('SI', True), ('NO', False)], default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso_foto', to='core.curso')),
            ],
        ),
        migrations.RemoveField(
            model_name='capacitacionfoto',
            name='capacitacion',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='capacitacion',
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
        migrations.DeleteModel(
            name='CapacitacionFoto',
        ),
        migrations.AddField(
            model_name='asistente',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asistentes', to='core.curso'),
            preserve_default=False,
        ),
    ]
