# Generated by Django 4.0.4 on 2025-01-07 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_curso_cursofoto_remove_capacitacionfoto_capacitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='estatus',
            field=models.BooleanField(choices=[('SI', True), ('NO', False)], default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
