# Generated by Django 4.0.4 on 2024-12-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_catalogo_curso_alter_capacitacion_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='unidad_duracion',
            field=models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5),
        ),
    ]
