# Generated by Django 4.0.4 on 2024-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_curso_unidad_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='temario',
        ),
        migrations.AddField(
            model_name='curso',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='temario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
