# Generated by Django 4.0.4 on 2025-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instructor_estatus_instructor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='estatus',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
    ]
