# Generated by Django 4.0.4 on 2025-01-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_instructor_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estado',
            new_name='estatus',
        ),
    ]
