# Generated by Django 4.0.4 on 2024-12-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_capacitacion_temario_curso_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='core.instructor'),
        ),
    ]
