# Generated by Django 4.0.4 on 2025-01-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_estado_curso_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estatus',
            new_name='estado',
        ),
    ]
