# Generated by Django 4.0.4 on 2024-12-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_capacitacion_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogo', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitaciones', to='core.instructor'),
        ),
    ]
