# Generated by Django 4.0.4 on 2024-12-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_capacitacion_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_capacitacion', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistentes', to='core.capacitacion'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso_capacitacion', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_capacitacion', to='core.instructor'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='asistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='core.asistente'),
        ),
    ]
