# Generated by Django 4.0.4 on 2024-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_capacitacion_empresa_alter_asistente_capacitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='hora_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='horas_diarias',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_diarias',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
