# Generated by Django 4.0.4 on 2024-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_capacitacion_hora_inicial_capacitacion_horas_diarias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='hora_inicial',
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
