# Generated by Django 4.0.4 on 2024-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_capacitacion_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
