# Generated by Django 4.0.4 on 2024-12-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empresa_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='activar_evaluacion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
    ]
