# Generated by Django 4.0.4 on 2024-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_capacitacion_activar_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
