# Generated by Django 4.0.4 on 2024-12-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_asistente_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion_Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('puntuacion', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_asistente', to='core.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='asistente',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_curso', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='activar_evaluacion',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('XX', 'XX')], default='NO', max_length=2),
        ),
        migrations.CreateModel(
            name='Evaluacion_Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('correcta', models.BooleanField(default=False)),
                ('evaluacion_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_respuestas', to='core.evaluacion_pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion_pregunta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_preguntas', to='core.evaluacion'),
        ),
        migrations.CreateModel(
            name='Evaluacion_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('evaluacion_asistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_detalle', to='core.evaluacion_asistente')),
            ],
        ),
    ]
