# Generated by Django 4.0.4 on 2024-12-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evaluacion_asistente_evaluacion_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='curso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_curso', to='core.curso'),
        ),
        migrations.AlterField(
            model_name='evaluacion_pregunta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_preguntas', to='core.evaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluacion_respuestas',
            name='evaluacion_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_respuestas', to='core.evaluacion_pregunta'),
        ),
    ]
