# Generated by Django 4.0.4 on 2024-12-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_evaluacion_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.TextField()),
                ('correctas', models.IntegerField(default=0)),
                ('incorrectas', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asistente', to='core.asistente')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_asistentes', to='core.evaluacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Evaluacion_Detalle',
        ),
    ]
