# Generated by Django 4.0.4 on 2024-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_respuestaasistente_delete_evaluacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaasistente',
            name='respuestas',
            field=models.JSONField(),
        ),
    ]
