# Generated by Django 4.0.4 on 2024-12-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_respuestaasistente_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='ACTIVO',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2),
        ),
    ]
