# Generated by Django 4.0.4 on 2024-12-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_asistente_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistente',
            old_name='ACTIVO',
            new_name='activo',
        ),
    ]
