# Generated by Django 4.0.4 on 2024-12-12 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_activo_asistente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('activar_evaluacion', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_foto', to='core.capacitacion')),
            ],
        ),
    ]
