# Generated by Django 4.0.4 on 2024-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_capacitacionfoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacitacionfoto',
            old_name='activar_evaluacion',
            new_name='activar_para_reporte',
        ),
        migrations.AlterField(
            model_name='capacitacionfoto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Capacitacion/', verbose_name='Foto'),
        ),
    ]
