# Generated by Django 4.0.4 on 2024-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_activar_evaluacion_capacitacionfoto_activar_para_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacionfoto',
            name='activar_para_reporte',
            field=models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=True),
        ),
    ]
