# Generated by Django 4.0.4 on 2024-12-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_capacitacionfoto_activar_para_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacionfoto',
            name='activar_para_reporte',
            field=models.BooleanField(choices=[('SI', True), ('NO', False)], default=True),
        ),
    ]
