# Generated by Django 4.0.4 on 2024-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_capacitacionfoto_activar_para_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='unidad_duracion',
            field=models.CharField(choices=[('Horas', 'Horas'), ('Días', 'Días')], default='Horas', max_length=5),
        ),
    ]
