# Generated by Django 4.0.4 on 2024-12-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_capacitacion_unidad_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='horas_diarias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
